"""add report_count and is_flagged to posts

Revision ID: f77abf7475c5
Revises: 
Create Date: 2026-07-30 12:44:05.746185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77abf7475c5'
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"     # 08312026: updated to reference the correct migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('report_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_flagged')
    op.drop_column('posts', 'report_count')
    # ### end Alembic commands ###
